name = Homepage
description = Homepage layout.
preview = preview.png
template = homepage-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[col_1]  = First column
regions[col_2] = Second column
regions[col_3] = Third column
regions[content_more]   = Further content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/homepage/homepage.styles.css
stylesheets[all][] = css/layouts/homepage/homepage.styles.no-query.css
